jobs:
- job: Windows_CI
  displayName: 'Windows CI'
  pool:
    #vmImage: 'vs2015-win2012r2'
    vmImage: 'vs2017-win2016'
  strategy:
    matrix: 
      Python36x86:
        python.version: '3.6'
        python.arch: x86
        addToPath: true
      Python37x86:
        python.version: '3.7'
        python.arch: x86
        addToPath: true
      Python36x64:
        python.version: '3.6'
        python.arch: x64
        addToPath: true
      Python37x64:
        python.version: '3.7'
        python.arch: x64
        addToPath: true
    maxParallel: 4


  variables: {'PYTHONUNBUFFERED': '1'}

  steps:
  - checkout: self
    submodules: recursive

  - task: UsePythonVersion@0
    inputs: 
      versionSpec: '$(python.version)'
      architecture: '$(python.arch)'

  # - script: |
  #     curl -O https://bootstrap.pypa.io/get-pip.py
  #     $PYTHON get-pip.py
  #     $PYTHON -m pip install setuptools wheel 
  #     $PYTHON -m pip install -r requirements.txt
  #   displayName: 'Install Python dependencies'

  # - script: |
  #     #sudo xcode-select -s /Applications/Xcode_9.4.1.app/Contents/Developer
  #     #xcode-select -p
  #     $PYTHON build.py --jobs=4 build_wx
  #   displayName: 'build wxWidgets'

  # - script: |
  #     $PYTHON build.py dox etg --nodoc sip
  #     $PYTHON build.py --jobs=4 build_py
  #   displayName: 'build wxPython'

  # - script: |
  #     $PYTHON build.py bdist_wheel
  #     sudo $PYTHON build.py install
  #     $PYTHON -c "import wx; print(wx.version());"
  #   displayName: 'build wheel and test install'
