jobs:
- job: MacOS-CI
  displayName: 'MacOS CI'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix: 
      Python27:
        python_version: '2.7.15'
        python_pkg: 'python-2.7.15-macosx10.9.pkg'
        python: 'python2.7'
      Python36:
        python_version: '3.6.6'
        python_pkg: 'python-3.6.6-macosx10.9.pkg'
        python: 'python3.6'
      Python37:
        python_version: '3.7.0'
        python_pkg: 'python-3.7.0-macosx10.9.pkg'
        python: 'python3.7'
    maxParallel: 3


  variables: {'PYTHONUNBUFFERED': '1'}

  steps:
  - checkout: self
    submodules: recursive

  - script: |
      curl -O https://www.python.org/ftp/python/$PYTHON_VERSION/$PYTHON_PKG
      sudo installer -pkg $PYTHON_PKG -target /
      which $PYTHON
      $PYTHON --version
    displayName: 'Fetch Python'

  - script: |
      curl -O https://bootstrap.pypa.io/get-pip.py
      $PYTHON get-pip.py
      $PYTHON -m pip install setuptools wheel 
      $PYTHON -m pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      #sudo xcode-select -s /Applications/Xcode_9.4.1.app/Contents/Developer
      #xcode-select -p
      $PYTHON build.py --jobs=4 build_wx
    displayName: 'build wxWidgets'

  - script: |
      $PYTHON build.py dox etg --nodoc sip
      $PYTHON build.py --jobs=4 build_py
    displayName: 'build wxPython'

  - script: |
      $PYTHON build.py bdist_wheel
      sudo $PYTHON build.py install
      $PYTHON -c "import wx; print(wx.version());"
    displayName: 'build wheel and test install'
